<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perftest.proto

namespace GPBMetadata;

class Perftest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0020a0e70657266746573742e70726f746f12166d6167656e746f2e63" .
            "7573746f6d65722e6d6f64656c22190a08546f6b656e417267120d0a0574" .
            "6f6b656e18012001280922470a0c437573746f6d65724461746112120a0a" .
            "637573746f6d6572496418012001280912110a0966697273744e616d6518" .
            "022001280912100a086c6173744e616d6518032001280922640a0d546f6b" .
            "656e526573706f6e736512120a0a746f6b656e466f756e64180120012808" .
            "12350a05666f756e6418022001280b32242e6d6167656e746f2e63757374" .
            "6f6d65722e6d6f64656c2e437573746f6d657244617461480042080a0672" .
            "6573756c7432640a0b417574685365727669636512550a0a696e74726f73" .
            "7065637412202e6d6167656e746f2e637573746f6d65722e6d6f64656c2e" .
            "546f6b656e4172671a252e6d6167656e746f2e637573746f6d65722e6d6f" .
            "64656c2e546f6b656e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

