<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: perftest.proto

namespace Magento\Customer\Model;

use Spiral\GRPC;

interface AuthServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "magento.customer.model.AuthService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TokenArg $in
    * @return TokenResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function introspect(GRPC\ContextInterface $ctx, TokenArg $in): TokenResponse;
}
