<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perftest.proto

namespace Magento\Customer\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.customer.model.CustomerData</code>
 */
class CustomerData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     */
    private $customerId = '';
    /**
     * Generated from protobuf field <code>string firstName = 2;</code>
     */
    private $firstName = '';
    /**
     * Generated from protobuf field <code>string lastName = 3;</code>
     */
    private $lastName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customerId
     *     @type string $firstName
     *     @type string $lastName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Perftest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customerId;
    }

    /**
     * Generated from protobuf field <code>string customerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string firstName = 2;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Generated from protobuf field <code>string firstName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastName = 3;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Generated from protobuf field <code>string lastName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastName = $var;

        return $this;
    }

}

